console-server: add ifdef around offsetof
GCC 12.2 seems to supply offsetof inside `stddef.h`.  Add guards
around the define here so that we do not end up with the following
compiler warnings:

```
22:35:49 | ../git/console-server.h:153: error: "offsetof" redefined [-Werror]
```

Change-Id: Id8d940db441a7ee96caf0a9a66e1ef3863cd3d2e
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>